name: Update ASN and IP List

on:
  push:
  workflow_dispatch:
  schedule:
    - cron: "10 04 * * FRI"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Set up Python 3.8
        uses: actions/setup-python@v4
        with:
          python-version: 3.8
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests lxml
      - name: Run Python
        run: |
          python getListASN.py
          python getPrefix.py
      - uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Update IP List
          file_pattern: ./*.list
          skip_dirty_check: false

